name: Run Selenium Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code from github
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Create a test report folder
        run: mkdir -p report

      - name: Run tests
        run: pytest -m smoke --html=report/report.html --self-contained-html

      - name: Upload file report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Pytest Report
          path: report/report.html